# Generated by Django 3.0.4 on 2020-03-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Horror', 'Horror'), ('LoveStory', 'LoveStory'), ('Commed', 'Commed'), ('Adventure', 'Adventure')], default='Action', max_length=100)),
                ('year_published', models.CharField(max_length=10)),
                ('logo', models.ImageField(default='movie.png', upload_to='uploads/logo')),
                ('moviefile', models.FileField(upload_to='uploads/files')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
