# Generated by Django 3.0.4 on 2020-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Sci-fi', 'Sci-fi'), ('Horror', 'Horror'), ('LoveStory', 'LoveStory'), ('Commed', 'Commed'), ('Adventure', 'Adventure')], default='Action', max_length=100),
        ),
    ]
